apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.hykube.io
spec:
  insecureSkipTLSVerify: true
  group: hykube.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: hykube
  version: v1alpha1
