apiVersion: apps/v1
kind: Deployment
metadata:
  name: hykube-server
  namespace: hykube
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      volumes:
        - name: hykube-provider-storage
          persistentVolumeClaim:
            claimName: hykube-provider-pvc
      containers:
      - name: hykube-server
        image: hykube-apiserver:latest
        imagePullPolicy: Never
        volumeMounts:
          - mountPath: "/data"
            name: hykube-provider-storage
