apiVersion: v1
kind: PersistentVolume
metadata:
  name: hykube-provider-pv
spec:
  capacity:
    storage: 5Gi # ensure there's enough space for e.g. terraform providers with many versions
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/hykube-provider-data"

