//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 by infrapot

This program is a free software product. You can redistribute it and/or
modify it under the terms of the GNU Affero General Public License (AGPL)
version 3 as published by the Free Software Foundation.

For details, see the GNU AGPL at: http://www.gnu.org/licenses/agpl-3.0.html
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	hykube "github.com/infrapot/hykube/pkg/apis/hykube"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Plan)(nil), (*hykube.Plan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Plan_To_hykube_Plan(a.(*Plan), b.(*hykube.Plan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hykube.Plan)(nil), (*Plan)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hykube_Plan_To_v1alpha1_Plan(a.(*hykube.Plan), b.(*Plan), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlanList)(nil), (*hykube.PlanList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlanList_To_hykube_PlanList(a.(*PlanList), b.(*hykube.PlanList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hykube.PlanList)(nil), (*PlanList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hykube_PlanList_To_v1alpha1_PlanList(a.(*hykube.PlanList), b.(*PlanList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*PlanSpec)(nil), (*hykube.PlanSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_PlanSpec_To_hykube_PlanSpec(a.(*PlanSpec), b.(*hykube.PlanSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hykube.PlanSpec)(nil), (*PlanSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hykube_PlanSpec_To_v1alpha1_PlanSpec(a.(*hykube.PlanSpec), b.(*PlanSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Provider)(nil), (*hykube.Provider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Provider_To_hykube_Provider(a.(*Provider), b.(*hykube.Provider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hykube.Provider)(nil), (*Provider)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hykube_Provider_To_v1alpha1_Provider(a.(*hykube.Provider), b.(*Provider), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProviderList)(nil), (*hykube.ProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProviderList_To_hykube_ProviderList(a.(*ProviderList), b.(*hykube.ProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hykube.ProviderList)(nil), (*ProviderList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hykube_ProviderList_To_v1alpha1_ProviderList(a.(*hykube.ProviderList), b.(*ProviderList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ProviderPlanDetails)(nil), (*hykube.ProviderPlanDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProviderPlanDetails_To_hykube_ProviderPlanDetails(a.(*ProviderPlanDetails), b.(*hykube.ProviderPlanDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*hykube.ProviderPlanDetails)(nil), (*ProviderPlanDetails)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hykube_ProviderPlanDetails_To_v1alpha1_ProviderPlanDetails(a.(*hykube.ProviderPlanDetails), b.(*ProviderPlanDetails), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*hykube.ProviderSpec)(nil), (*ProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_hykube_ProviderSpec_To_v1alpha1_ProviderSpec(a.(*hykube.ProviderSpec), b.(*ProviderSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddConversionFunc((*ProviderSpec)(nil), (*hykube.ProviderSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ProviderSpec_To_hykube_ProviderSpec(a.(*ProviderSpec), b.(*hykube.ProviderSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Plan_To_hykube_Plan(in *Plan, out *hykube.Plan, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_PlanSpec_To_hykube_PlanSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_v1alpha1_Plan_To_hykube_Plan is an autogenerated conversion function.
func Convert_v1alpha1_Plan_To_hykube_Plan(in *Plan, out *hykube.Plan, s conversion.Scope) error {
	return autoConvert_v1alpha1_Plan_To_hykube_Plan(in, out, s)
}

func autoConvert_hykube_Plan_To_v1alpha1_Plan(in *hykube.Plan, out *Plan, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_hykube_PlanSpec_To_v1alpha1_PlanSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	return nil
}

// Convert_hykube_Plan_To_v1alpha1_Plan is an autogenerated conversion function.
func Convert_hykube_Plan_To_v1alpha1_Plan(in *hykube.Plan, out *Plan, s conversion.Scope) error {
	return autoConvert_hykube_Plan_To_v1alpha1_Plan(in, out, s)
}

func autoConvert_v1alpha1_PlanList_To_hykube_PlanList(in *PlanList, out *hykube.PlanList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]hykube.Plan)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PlanList_To_hykube_PlanList is an autogenerated conversion function.
func Convert_v1alpha1_PlanList_To_hykube_PlanList(in *PlanList, out *hykube.PlanList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlanList_To_hykube_PlanList(in, out, s)
}

func autoConvert_hykube_PlanList_To_v1alpha1_PlanList(in *hykube.PlanList, out *PlanList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Plan)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_hykube_PlanList_To_v1alpha1_PlanList is an autogenerated conversion function.
func Convert_hykube_PlanList_To_v1alpha1_PlanList(in *hykube.PlanList, out *PlanList, s conversion.Scope) error {
	return autoConvert_hykube_PlanList_To_v1alpha1_PlanList(in, out, s)
}

func autoConvert_v1alpha1_PlanSpec_To_hykube_PlanSpec(in *PlanSpec, out *hykube.PlanSpec, s conversion.Scope) error {
	out.Provider = in.Provider
	return nil
}

// Convert_v1alpha1_PlanSpec_To_hykube_PlanSpec is an autogenerated conversion function.
func Convert_v1alpha1_PlanSpec_To_hykube_PlanSpec(in *PlanSpec, out *hykube.PlanSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PlanSpec_To_hykube_PlanSpec(in, out, s)
}

func autoConvert_hykube_PlanSpec_To_v1alpha1_PlanSpec(in *hykube.PlanSpec, out *PlanSpec, s conversion.Scope) error {
	out.Provider = in.Provider
	return nil
}

// Convert_hykube_PlanSpec_To_v1alpha1_PlanSpec is an autogenerated conversion function.
func Convert_hykube_PlanSpec_To_v1alpha1_PlanSpec(in *hykube.PlanSpec, out *PlanSpec, s conversion.Scope) error {
	return autoConvert_hykube_PlanSpec_To_v1alpha1_PlanSpec(in, out, s)
}

func autoConvert_v1alpha1_Provider_To_hykube_Provider(in *Provider, out *hykube.Provider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ProviderSpec_To_hykube_ProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	out.Filename = in.Filename
	return nil
}

// Convert_v1alpha1_Provider_To_hykube_Provider is an autogenerated conversion function.
func Convert_v1alpha1_Provider_To_hykube_Provider(in *Provider, out *hykube.Provider, s conversion.Scope) error {
	return autoConvert_v1alpha1_Provider_To_hykube_Provider(in, out, s)
}

func autoConvert_hykube_Provider_To_v1alpha1_Provider(in *hykube.Provider, out *Provider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_hykube_ProviderSpec_To_v1alpha1_ProviderSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	out.Status = in.Status
	out.Filename = in.Filename
	return nil
}

// Convert_hykube_Provider_To_v1alpha1_Provider is an autogenerated conversion function.
func Convert_hykube_Provider_To_v1alpha1_Provider(in *hykube.Provider, out *Provider, s conversion.Scope) error {
	return autoConvert_hykube_Provider_To_v1alpha1_Provider(in, out, s)
}

func autoConvert_v1alpha1_ProviderList_To_hykube_ProviderList(in *ProviderList, out *hykube.ProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]hykube.Provider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_Provider_To_hykube_Provider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_ProviderList_To_hykube_ProviderList is an autogenerated conversion function.
func Convert_v1alpha1_ProviderList_To_hykube_ProviderList(in *ProviderList, out *hykube.ProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProviderList_To_hykube_ProviderList(in, out, s)
}

func autoConvert_hykube_ProviderList_To_v1alpha1_ProviderList(in *hykube.ProviderList, out *ProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provider, len(*in))
		for i := range *in {
			if err := Convert_hykube_Provider_To_v1alpha1_Provider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_hykube_ProviderList_To_v1alpha1_ProviderList is an autogenerated conversion function.
func Convert_hykube_ProviderList_To_v1alpha1_ProviderList(in *hykube.ProviderList, out *ProviderList, s conversion.Scope) error {
	return autoConvert_hykube_ProviderList_To_v1alpha1_ProviderList(in, out, s)
}

func autoConvert_v1alpha1_ProviderPlanDetails_To_hykube_ProviderPlanDetails(in *ProviderPlanDetails, out *hykube.ProviderPlanDetails, s conversion.Scope) error {
	out.Name = in.Name
	out.Config = in.Config
	return nil
}

// Convert_v1alpha1_ProviderPlanDetails_To_hykube_ProviderPlanDetails is an autogenerated conversion function.
func Convert_v1alpha1_ProviderPlanDetails_To_hykube_ProviderPlanDetails(in *ProviderPlanDetails, out *hykube.ProviderPlanDetails, s conversion.Scope) error {
	return autoConvert_v1alpha1_ProviderPlanDetails_To_hykube_ProviderPlanDetails(in, out, s)
}

func autoConvert_hykube_ProviderPlanDetails_To_v1alpha1_ProviderPlanDetails(in *hykube.ProviderPlanDetails, out *ProviderPlanDetails, s conversion.Scope) error {
	out.Name = in.Name
	out.Config = in.Config
	return nil
}

// Convert_hykube_ProviderPlanDetails_To_v1alpha1_ProviderPlanDetails is an autogenerated conversion function.
func Convert_hykube_ProviderPlanDetails_To_v1alpha1_ProviderPlanDetails(in *hykube.ProviderPlanDetails, out *ProviderPlanDetails, s conversion.Scope) error {
	return autoConvert_hykube_ProviderPlanDetails_To_v1alpha1_ProviderPlanDetails(in, out, s)
}

func autoConvert_v1alpha1_ProviderSpec_To_hykube_ProviderSpec(in *ProviderSpec, out *hykube.ProviderSpec, s conversion.Scope) error {
	out.DownloadName = in.DownloadName
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.DownloadUrl = (*string)(unsafe.Pointer(in.DownloadUrl))
	return nil
}

func autoConvert_hykube_ProviderSpec_To_v1alpha1_ProviderSpec(in *hykube.ProviderSpec, out *ProviderSpec, s conversion.Scope) error {
	out.DownloadName = in.DownloadName
	out.Version = (*string)(unsafe.Pointer(in.Version))
	out.DownloadUrl = (*string)(unsafe.Pointer(in.DownloadUrl))
	return nil
}
